# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1000, 856)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo.sizePolicy().hasHeightForWidth())
        self.photo.setSizePolicy(sizePolicy)
        self.photo.setMinimumSize(QtCore.QSize(940, 640))
        self.photo.setStyleSheet("border: 5px solid white;")
        self.photo.setText("")
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.photo.setWordWrap(False)
        self.photo.setObjectName("photo")
        self.verticalLayout.addWidget(self.photo)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Back_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back_btn.sizePolicy().hasHeightForWidth())
        self.Back_btn.setSizePolicy(sizePolicy)
        self.Back_btn.setMinimumSize(QtCore.QSize(185, 185))
        self.Back_btn.setStyleSheet("QPushButton{\n"
" background-color: white;\n"
" color: black;\n"
" border: 2px solid #555555;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: #555555;\n"
"color: white;\n"
"}")
        self.Back_btn.setText("")
        self.Back_btn.setIconSize(QtCore.QSize(100, 100))
        self.Back_btn.setObjectName("Back_btn")
        self.horizontalLayout_2.addWidget(self.Back_btn)
        self.Select_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Select_btn.sizePolicy().hasHeightForWidth())
        self.Select_btn.setSizePolicy(sizePolicy)
        self.Select_btn.setMinimumSize(QtCore.QSize(185, 185))
        self.Select_btn.setStyleSheet("QPushButton{\n"
" background-color: white;\n"
" color: black;\n"
" border: 2px solid #555555;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: #555555;\n"
"color: white;\n"
"}")
        self.Select_btn.setText("")
        self.Select_btn.setIconSize(QtCore.QSize(100, 100))
        self.Select_btn.setObjectName("Select_btn")
        self.horizontalLayout_2.addWidget(self.Select_btn)
        self.Run_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Run_btn.sizePolicy().hasHeightForWidth())
        self.Run_btn.setSizePolicy(sizePolicy)
        self.Run_btn.setMinimumSize(QtCore.QSize(185, 185))
        self.Run_btn.setStyleSheet("QPushButton{\n"
" background-color: white;\n"
" color: black;\n"
" border: 2px solid #555555;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: #555555;\n"
"color: white;\n"
"}")
        self.Run_btn.setText("")
        self.Run_btn.setIconSize(QtCore.QSize(100, 100))
        self.Run_btn.setObjectName("Run_btn")
        self.horizontalLayout_2.addWidget(self.Run_btn)
        self.Original_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Original_btn.sizePolicy().hasHeightForWidth())
        self.Original_btn.setSizePolicy(sizePolicy)
        self.Original_btn.setMinimumSize(QtCore.QSize(185, 185))
        self.Original_btn.setStyleSheet("QPushButton{\n"
" background-color: white;\n"
" color: black;\n"
" border: 2px solid #555555;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: #555555;\n"
"color: white;\n"
"}")
        self.Original_btn.setText("")
        self.Original_btn.setIconSize(QtCore.QSize(100, 100))
        self.Original_btn.setObjectName("Original_btn")
        self.horizontalLayout_2.addWidget(self.Original_btn)
        self.Front_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Front_btn.sizePolicy().hasHeightForWidth())
        self.Front_btn.setSizePolicy(sizePolicy)
        self.Front_btn.setMinimumSize(QtCore.QSize(185, 185))
        self.Front_btn.setStyleSheet("QPushButton{\n"
" background-color: white;\n"
" color: black;\n"
" border: 2px solid #555555;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: #555555;\n"
"color: white;\n"
"}")
        self.Front_btn.setText("")
        self.Front_btn.setIconSize(QtCore.QSize(100, 100))
        self.Front_btn.setObjectName("Front_btn")
        self.horizontalLayout_2.addWidget(self.Front_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_12.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
